#!/usr/bin/env python3
"""Build the demo discs: one per player, each with a song and a !BOOT.

    python example/build.py                 # both, with the default songs
    python example/build.py --player aky --song path/to/song.aks

Run from the REPO ROOT. Produces build/ARKOS-AKL.SSD and build/ARKOS-AKY.SSD;
boot either with SHIFT-BREAK.

Each disc is one file: the code, then the song assembled at &3000. The song
has to be exported at the address it is played from, which is why this
script exists at all rather than a one-line beebasm invocation.
"""

import argparse
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
BUILD = os.path.join(HERE, 'build')
sys.path.insert(0, os.path.join(ROOT, 'tools', 'verify'))

SONG_ADDR = 0x3000

HOME = os.path.expanduser('~')
AT3 = os.environ.get('ARKOS3_HOME',
                     os.path.join(HOME, 'OneDrive', 'Trackers', 'ArkosTracker3'))
BEEB = os.path.dirname(os.path.dirname(ROOT))

# The defaults. AKL gets a Targhan song because Arkos Tracker 2's AKL
# exporter cannot correctly export the Rhino tune - see docs/format-akl.md.
DEFAULTS = {
    'akl': (os.path.join(AT3, 'songs', 'STarKos',
                         'Targhan - Dead On Time - Ingame.sks'),
            'Targhan - Dead On Time (Ingame)'),
    'aky': (os.path.join(ROOT, 'songs', 'Acid_demo_07.aks'),
            'Rhino - Acid Demo'),
}


def beebasm():
    for c in (os.path.join(ROOT, 'bin', 'beebasm.exe'),
              os.path.join(BEEB, 'Bin', 'beebasm.exe')):
        if os.path.exists(c):
            return c
    return 'beebasm'


def export(song, player, out):
    if player == 'akl':
        subprocess.run([sys.executable, os.path.join(ROOT, 'tools', 'export_akl.py'),
                        song, '--addr', hex(SONG_ADDR), '-o', out],
                       cwd=ROOT, check=True, stdout=subprocess.DEVNULL)
    else:
        exe = os.path.join(AT3, 'tools', 'SongToAky.exe')
        r = subprocess.run([exe, '-s', '1', '-bin', '-adr', hex(SONG_ADDR), song, out],
                           capture_output=True, text=True)
        if r.returncode != 0:
            sys.stderr.write(r.stdout + r.stderr)
            raise SystemExit('SongToAky failed')


def aky_psgs(path):
    """Three channels make a PSG. The player handles the rest itself."""
    return (open(path, 'rb').read()[1] + 2) // 3


def build(player, song, title):
    os.makedirs(BUILD, exist_ok=True)
    binary = os.path.join(BUILD, 'song.bin')
    export(song, player, binary)
    if player == 'aky':
        n = aky_psgs(binary)
        if n > 1:
            print('  %d PSGs: playing the first, ignoring %d more channels'
                  % (n, 3 * (n - 1)))

    with open(os.path.join(BUILD, 'config.asm'), 'w') as f:
        f.write('\\ Generated by example/build.py - do not edit.\n')
        f.write('PLAYER_AKY = %d\n' % (player == 'aky'))
        f.write('SONG_TITLE = "%s"\n' % title.replace('"', "'"))

    name = 'AKYDEMO' if player == 'aky' else 'AKLDEMO'
    with open(os.path.join(BUILD, 'boot.txt'), 'w') as f:
        f.write('*BASIC\r*RUN %s\r' % name)

    ssd = os.path.join(ROOT, 'build', 'ARKOS-%s.SSD' % player.upper())
    os.makedirs(os.path.dirname(ssd), exist_ok=True)
    r = subprocess.run([beebasm(), '-i', 'example/demo.asm', '-do', ssd,
                        '-boot', name, '-title', 'ARKOS', '-opt', '3'],
                       cwd=ROOT, capture_output=True, text=True)
    sys.stdout.write(r.stdout)
    if r.returncode != 0:
        sys.stderr.write(r.stderr)
        raise SystemExit('beebasm failed for %s' % player)
    print('%s: %s  (%s)' % (ssd, os.path.basename(song), title))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--player', choices=('akl', 'aky'))
    ap.add_argument('--song')
    ap.add_argument('--title', default=None)
    args = ap.parse_args()

    players = [args.player] if args.player else ['akl', 'aky']
    for p in players:
        song, title = DEFAULTS[p]
        if args.song:
            song = args.song
            title = args.title or os.path.splitext(os.path.basename(song))[0]
        if not os.path.exists(song):
            print('skipping %s: %s not found' % (p, song))
            continue
        build(p, song, title)


if __name__ == '__main__':
    sys.exit(main())
